# **1. Leer el libro original** : *Normalized_Global_Report*

In [ ]:
#Librería super importante

!pip install pymarc

Requirement already satisfied: pymarc in /usr/local/lib/python3.12/dist-packages (5.3.1)

In [ ]:
from pymarc import MARCReader
from google.colab import files
import pandas as pd

# URL del Google Sheet Normalized_Global_Report-reportresults extraigo de KOHA
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1Uu2Mst112a6QE5cuJw-KkHV_xDLRS9tB5kRM6ILodww/edit?gid=1474965563#gid=1474965563'

# Convertir la URL para que sea apta para lectura CSV
csv_export_url = google_sheet_url.replace('/edit?gid=', '/export?format=csv&gid=')

try:
    df_sheet = pd.read_csv(csv_export_url)
    print("Content of Google Sheet:")
    display(df_sheet.head())
except Exception as e:
    print(f"Error al leer el Google Sheet: {e}")
    print("Asegúrate de que la hoja de cálculo sea pública o que tu Google Drive esté montado y tengas los permisos adecuados.")

Content of Google Sheet:

,biblionumber,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,...,coau_institucion_1,coau_institucion_2,coau_institucion_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,branch_952_a,subbranch_952_b
0,13588,13588,NaN,NaN,NaN,NaN,spa,NaN,NaN,Oficina Nacional de Procesos Electorales 27,...,NaN,NaN,NaN,BKS,BKS,NaN,00001-001-INFO006BKS,NaN,ONPE,ONPE
1,13589,13589,NaN,NaN,NaN,NaN,spa,658.40985/I/2016,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,BKS,BKS,658.40985/I/2016,00002-001-INFOCHABKS,NaN,ONPE,ONPE
2,13590,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,MD,MD,V/0001/2020,00003-001-¡CON019BKS,NaN,ONPE,ONPE
3,13590,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,MD,MD,V/0001/2020,00003-002-¡CON019BKS,Ej.2,ONPE,ONPE
4,13590,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,MD,MD,V/0001/2020,00003-003-¡CON019BKS,Ej.3,ONPE,ONPE

# **2. Leer el Google Sheet con registros actualizados**

In [ ]:
from pymarc import MARCReader
from google.colab import files
import pandas as pd

# URL del Google Sheet Libros_Actualizados_Excel
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1_xtluQNjQGUs7mTXiNReB4UITdR2rFGoQaIpa6lu0ds/edit?gid=181236238#gid=181236238'

# Convertir la URL para que sea apta para lectura CSV
csv_export_url = google_sheet_url.replace('/edit?gid=', '/export?format=csv&gid=')

try:
    df_sheet = pd.read_csv(csv_export_url)
    print("Content of Google Sheet:")
    display(df_sheet.head())
except Exception as e:
    print(f"Error al leer el Google Sheet: {e}")
    print("Asegúrate de que la hoja de cálculo sea pública o que tu Google Drive esté montado y tengas los permisos adecuados.")

Content of Google Sheet:

,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,autor_congreso_111,...,coau_institucion_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,numero_copia_952_t.1,numero_copia_952_t.2,952_a,952_b
0,18551,NaN,NaN,NaN,NaN,NaN,324.640985/BEE/2018,NaN,Perú. Registro Nacional de Identificación y Es...,NaN,...,NaN,BKS,NaN,324.640985/BEE/2018,NaN,NaN,Ej. 2,NaN,ONPE,ONPE
1,14495,NaN,NaN,NaN,NaN,NaN,REF/352.02585/A81/2000,NaN,Asociación Civil Transparencia (Lima),NaN,...,NaN,BKS,NaN,REF/352.02585/A81/2000,NaN,NaN,NaN,NaN,ONPE,ONPE
2,14496,NaN,NaN,2015-13710,NaN,NaN,364.152/I59/2011-2014,NaN,Instituto Nacional de Estadística e Informátic...,NaN,...,NaN,BKS,NaN,364.152/I59/2011-2014,NaN,NaN,NaN,NaN,ONPE,ONPE
3,15732,NaN,NaN,2015-12936,NaN,NaN,330.985/I59/2011-2014,NaN,Instituto Nacional de Estadística e Informátic...,NaN,...,NaN,BKS,NaN,330.985/I59/2011-2014,NaN,NaN,NaN,NaN,ONPE,ONPE
4,16066,NaN,NaN,NaN,NaN,NaN,324.97293/J89/2012,NaN,República Dominicana. Junta Central Electoral,NaN,...,NaN,BKS,NaN,324.97293/J89/2012,NaN,NaN,NaN,NaN,ONPE,ONPE

# **3. Normalizar campos del libro original**
_para que esten igual que en el formato actualizado_

In [ ]:
import pandas as pd
from google.colab import files

# URL del Normalized_Global_Report
google_sheet_original_url = 'https://docs.google.com/spreadsheets/d/1Uu2Mst112a6QE5cuJw-KkHV_xDLRS9tB5kRM6ILodww/edit?gid=1474965563#gid=1474965563'
csv_export_original_url = google_sheet_original_url.replace('/edit?gid=', '/export?format=csv&gid=')

# URL del Google Sheet actualizado (para la referencia de columnas)
google_sheet_updated_url = 'https://docs.google.com/spreadsheets/d/1_xtluQNjQGUs7mTXiNReB4UITdR2rFGoQaIpa6lu0ds/edit?gid=181236238#gid=181236238'
csv_export_updated_url = google_sheet_updated_url.replace('/edit?gid=', '/export?format=csv&gid=')

# Cargar el Google Sheet original
try:
    df_original_sheet = pd.read_csv(csv_export_original_url)
    print("Content of Original Google Sheet:")
    display(df_original_sheet.head())

    # --- Modificaciones solicitadas por el usuario ---

    # 1. Eliminar la columna 'biblionumber' si existe
    if 'biblionumber' in df_original_sheet.columns:
        df_original_sheet = df_original_sheet.drop(columns=['biblionumber'])
        print("\nColumna 'biblionumber' eliminada.")

    # 2. Renombrar columnas
    rename_mapping = {
        'coau_institucion_1': 'coau_institución_1',
        'coau_institucion_2': 'coau_institución_2',
        'coau_institucion_3': 'coau_institución_3',
        'branch_952_a': '952_a'
    }
    df_original_sheet = df_original_sheet.rename(columns=rename_mapping)
    print("\nColumnas renombradas:")
    print(rename_mapping)

    # 3. Añadir columnas 'numero_copia_952_t', '952_b', 'numero_copia_952_t.1' y 'numero_copia_952_t.2' (si no existen)
    if 'numero_copia_952_t' not in df_original_sheet.columns:
        df_original_sheet['numero_copia_952_t'] = pd.NA
        print("Columna 'numero_copia_952_t' añadida.")
    if '952_b' not in df_original_sheet.columns:
        df_original_sheet['952_b'] = pd.NA
        print("Columna '952_b' añadida.")
    if 'numero_copia_952_t.1' not in df_original_sheet.columns:
        df_original_sheet['numero_copia_952_t.1'] = pd.NA
        print("Columna 'numero_copia_952_t.1' añadida.")
    if 'numero_copia_952_t.2' not in df_original_sheet.columns:
        df_original_sheet['numero_copia_952_t.2'] = pd.NA
        print("Columna 'numero_copia_952_t.2' añadida.")

    # --- Fin de las modificaciones solicitadas ---

except Exception as e:
    print(f"Error al leer el Google Sheet original: {e}")
    print("Asegúrate de que la hoja de cálculo sea pública o que tu Google Drive esté montado y tengas los permisos adecuados.")

# Cargar el Google Sheet actualizado para obtener sus columnas
try:
    df_updated_sheet = pd.read_csv(csv_export_updated_url)
    print("\nContent of Updated Google Sheet (for column reference):")
    display(df_updated_sheet.head())
except Exception as e:
    print(f"Error al leer el Google Sheet actualizado: {e}")
    print("Asegúrate de que la hoja de cálculo sea pública o que tu Google Drive esté montado y tengas los permisos adecuados.")

# Obtener las columnas del sheet actualizado
columns_to_keep = df_updated_sheet.columns.tolist()

# Filtrar el sheet original para mantener solo las columnas presentes en el sheet actualizado
df_normalized_global = df_original_sheet[df_original_sheet.columns.intersection(columns_to_keep)]

print("\nNormalized Global Sheet (first 5 rows):")
display(df_normalized_global.head())
print(f"Original columns: {len(df_original_sheet.columns)}")
print(f"Updated reference columns: {len(df_updated_sheet.columns)}")
print(f"Normalized columns: {len(df_normalized_global.columns)}")

# Guardar el DataFrame normalizado en un archivo CSV
output_filename = 'Normalized_Global_Sheet.csv'
df_normalized_global.to_csv(output_filename, index=False)

print(f"\nEl archivo '{output_filename}' ha sido creado exitosamente.")

Content of Original Google Sheet:

,biblionumber,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,...,coau_institucion_1,coau_institucion_2,coau_institucion_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,branch_952_a,subbranch_952_b
0,13588,13588,NaN,NaN,NaN,NaN,spa,NaN,NaN,Oficina Nacional de Procesos Electorales 27,...,NaN,NaN,NaN,BKS,BKS,NaN,00001-001-INFO006BKS,NaN,ONPE,ONPE
1,13589,13589,NaN,NaN,NaN,NaN,spa,658.40985/I/2016,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,BKS,BKS,658.40985/I/2016,00002-001-INFOCHABKS,NaN,ONPE,ONPE
2,13590,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,MD,MD,V/0001/2020,00003-001-¡CON019BKS,NaN,ONPE,ONPE
3,13590,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,MD,MD,V/0001/2020,00003-002-¡CON019BKS,Ej.2,ONPE,ONPE
4,13590,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,...,NaN,NaN,NaN,MD,MD,V/0001/2020,00003-003-¡CON019BKS,Ej.3,ONPE,ONPE

Columna 'biblionumber' eliminada.

Columnas renombradas:
{'coau_institucion_1': 'coau_institución_1', 'coau_institucion_2': 'coau_institución_2', 'coau_institucion_3': 'coau_institución_3', 'branch_952_a': '952_a'}
Columna '952_b' añadida.
Columna 'numero_copia_952_t.1' añadida.
Columna 'numero_copia_952_t.2' añadida.

Content of Updated Google Sheet (for column reference):

,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,autor_congreso_111,...,coau_institucion_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,numero_copia_952_t.1,numero_copia_952_t.2,952_a,952_b
0,18551,NaN,NaN,NaN,NaN,NaN,324.640985/BEE/2018,NaN,Perú. Registro Nacional de Identificación y Es...,NaN,...,NaN,BKS,NaN,324.640985/BEE/2018,NaN,NaN,Ej. 2,NaN,ONPE,ONPE
1,14495,NaN,NaN,NaN,NaN,NaN,REF/352.02585/A81/2000,NaN,Asociación Civil Transparencia (Lima),NaN,...,NaN,BKS,NaN,REF/352.02585/A81/2000,NaN,NaN,NaN,NaN,ONPE,ONPE
2,14496,NaN,NaN,2015-13710,NaN,NaN,364.152/I59/2011-2014,NaN,Instituto Nacional de Estadística e Informátic...,NaN,...,NaN,BKS,NaN,364.152/I59/2011-2014,NaN,NaN,NaN,NaN,ONPE,ONPE
3,15732,NaN,NaN,2015-12936,NaN,NaN,330.985/I59/2011-2014,NaN,Instituto Nacional de Estadística e Informátic...,NaN,...,NaN,BKS,NaN,330.985/I59/2011-2014,NaN,NaN,NaN,NaN,ONPE,ONPE
4,16066,NaN,NaN,NaN,NaN,NaN,324.97293/J89/2012,NaN,República Dominicana. Junta Central Electoral,NaN,...,NaN,BKS,NaN,324.97293/J89/2012,NaN,NaN,NaN,NaN,ONPE,ONPE

Normalized Global Sheet (first 5 rows):

,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,autor_congreso_111,...,coautor_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,952_a,952_b,numero_copia_952_t.1,numero_copia_952_t.2
0,13588,NaN,NaN,NaN,NaN,spa,NaN,NaN,Oficina Nacional de Procesos Electorales 27,NaN,...,NaN,BKS,BKS,NaN,00001-001-INFO006BKS,NaN,ONPE,<NA>,<NA>,<NA>
1,13589,NaN,NaN,NaN,NaN,spa,658.40985/I/2016,NaN,Oficina Nacional de Procesos Electorales,NaN,...,NaN,BKS,BKS,658.40985/I/2016,00002-001-INFOCHABKS,NaN,ONPE,<NA>,<NA>,<NA>
2,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,NaN,...,NaN,MD,MD,V/0001/2020,00003-001-¡CON019BKS,NaN,ONPE,<NA>,<NA>,<NA>
3,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,NaN,...,NaN,MD,MD,V/0001/2020,00003-002-¡CON019BKS,Ej.2,ONPE,<NA>,<NA>,<NA>
4,13590,NaN,NaN,2019-18195,NaN,spa,V/0001/2020,NaN,Oficina Nacional de Procesos Electorales,NaN,...,NaN,MD,MD,V/0001/2020,00003-003-¡CON019BKS,Ej.3,ONPE,<NA>,<NA>,<NA>

Original columns: 56
Updated reference columns: 55
Normalized columns: 51

El archivo 'Normalized_Global_Sheet.csv' ha sido creado exitosamente.

# **4. Limpieza de datos**

In [ ]:
import pandas as pd

# --- URLs de los Google Sheets ---
# Sheet A: el documento con los datos a integrar
url_sheet_a = 'https://docs.google.com/spreadsheets/d/1_xtluQNjQGUs7mTXiNReB4UITdR2rFGoQaIpa6lu0ds/edit?gid=181236238#gid=181236238'
csv_export_sheet_a = url_sheet_a.replace('/edit?gid=', '/export?format=csv&gid=')

# --- 1. Cargar el Google Sheet de Actualizaciones (Sheet A) ---
try:
    # Cargar Sheet A, asegurando que 'biblionumber_999_c' sea tipo string para una fusión consistente
    df_new_updates = pd.read_csv(csv_export_sheet_a, dtype={'biblionumber_999_c': str})
    print("Contenido del Google Sheet de Actualizaciones (Sheet A):")
    display(df_new_updates.head())

    # Limpiar espacios en blanco de 'biblionumber_999_c' para la fusión
    df_new_updates['biblionumber_999_c'] = df_new_updates['biblionumber_999_c'].astype(str).str.strip()

    # Renombrar 'subbranch_952_b' a '952_b' en df_new_updates para que coincida
    if 'subbranch_952_b' in df_new_updates.columns:
        df_new_updates = df_new_updates.rename(columns={'subbranch_952_b': '952_b'})
        print("\nColumna 'subbranch_952_b' renombrada a '952_b' en df_new_updates.")

except Exception as e:
    print(f"Error al leer el Google Sheet de Actualizaciones (Sheet A): {e}")
    print("Asegúrate de que la hoja de cálculo sea pública o que tu Google Drive esté montado y tengas los permisos adecuados.")
    # Detener la ejecución si no se puede cargar el archivo vital
    raise

# --- Preparar df_normalized_global (Sheet B, el documento antiguo normalizado) ---
# df_normalized_global debería estar disponible de celdas anteriores.
# Aseguramos que 'biblionumber_999_c' sea tipo string para una fusión consistente
if 'df_normalized_global' in locals() and isinstance(df_normalized_global, pd.DataFrame):
    df_current_global = df_normalized_global.copy()
    df_current_global['biblionumber_999_c'] = df_current_global['biblionumber_999_c'].astype(str).str.strip()
else:
    print("Error: 'df_normalized_global' no se encontró o no es un DataFrame. Asegúrate de ejecutar las celdas anteriores.")
    raise ValueError("'df_normalized_global' no está disponible.")

# --- 3. Filtrar df_current_global para biblionumber_999_c que coinciden (condición 1 y 3) ---
# Obtener los biblionumber_999_c únicos del sheet de actualizaciones
biblio_nums_in_updates = df_new_updates['biblionumber_999_c'].dropna().unique()

# Filtrar df_current_global para mantener solo los biblionumber_999_c presentes en df_new_updates
df_filtered_global = df_current_global[df_current_global['biblionumber_999_c'].isin(biblio_nums_in_updates)].copy()

print(f"\nDataFrame filtrado basado en {len(biblio_nums_in_updates)} biblionumbers únicos de la hoja de actualizaciones:")
display(df_filtered_global.head())
print(f"Número de filas después del filtro: {len(df_filtered_global)}")

# --- 4. Alertar sobre biblionumber_999_c en Sheet A que no están en Sheet B ---
biblio_nums_in_filtered_global = df_filtered_global['biblionumber_999_c'].dropna().unique()
missing_in_filtered_global = set(biblio_nums_in_updates) - set(biblio_nums_in_filtered_global)

if missing_in_filtered_global:
    print("\n--- ALERTA: Biblionumbers en la hoja de actualizaciones no encontrados en el documento global ---")
    for biblio_num in sorted(list(missing_in_filtered_global)):
        print(f"- {biblio_num}")
else:
    print("\nTodos los biblionumbers de la hoja de actualizaciones están presentes en el documento global.")

# --- Procesar ejemplares y colapsar filas duplicadas (nueva lógica) ---

# Calcular el número de copias por cada biblionumber ANTES de colapsar
copy_counts = df_filtered_global.groupby('biblionumber_999_c').size()

# Alerta para biblionumber_999_c con más de 3 ejemplares (utilizando copy_counts)
biblio_over_3_copies = copy_counts[copy_counts > 3].index.tolist()

if biblio_over_3_copies:
    print("\n--- ALERTA: Los siguientes biblionumbers tienen más de 3 ejemplares (se mostrarán solo hasta 'Ej. 3') ---")
    for biblio_num in sorted(biblio_over_3_copies):
        print(f"- {biblio_num}: {copy_counts[biblio_num]} ejemplares")
else:
    print("\nNingún biblionumber tiene más de 3 ejemplares.")

# Crear un DataFrame con una sola entrada por biblionumber, tomando la primera fila para el resto de los datos
# (como se solicitó: "solo quedate con la primera que aparece por cada biblionumber")
df_single_entry_global = df_filtered_global.groupby('biblionumber_999_c', as_index=False).first()

# Rellenar las columnas numero_copia_952_t, numero_copia_952_t.1 y numero_copia_952_t.2
# numero_copia_952_t debe ser vacío/NaN
df_single_entry_global['numero_copia_952_t'] = pd.NA

# numero_copia_952_t.1 debe ser 'Ej. 2' si hay 2 o más ejemplares
df_single_entry_global['numero_copia_952_t.1'] = df_single_entry_global['biblionumber_999_c'].map(
    lambda x: 'Ej. 2' if copy_counts.get(x, 0) >= 2 else pd.NA
)
# numero_copia_952_t.2 debe ser 'Ej. 3' si hay 3 o más ejemplares
df_single_entry_global['numero_copia_952_t.2'] = df_single_entry_global['biblionumber_999_c'].map(
    lambda x: 'Ej. 3' if copy_counts.get(x, 0) >= 3 else pd.NA
)

print("\nDataFrame procesado con ejemplares colapsados y columnas 'Ej.' actualizadas (primeras 5 filas):")
display(df_single_entry_global[['biblionumber_999_c', 'numero_copia_952_t', 'numero_copia_952_t.1', 'numero_copia_952_t.2']].head())

# Ahora, la integración debe hacerse con df_single_entry_global
df_updated_final = df_single_entry_global.copy()

# Columnas a excluir del proceso de actualización general desde df_new_updates
# Se excluyen las columnas de ejemplares porque su valor es generado por la lógica anterior.
columns_to_exclude_from_update = [
    'biblionumber_999_c',
    'numero_copia_952_t',
    'numero_copia_952_t.1',
    'numero_copia_952_t.2'
]

# Itera sobre cada fila de la hoja de actualizaciones
for index, row_update in df_new_updates.iterrows():
    biblio_to_update = str(row_update['biblionumber_999_c']).strip() # Ensure consistency

    # Encuentra el índice en df_updated_final que coincide con este biblionumber
    # Ahora solo habrá una fila por biblionumber
    target_index = df_updated_final[df_updated_final['biblionumber_999_c'] == biblio_to_update].index

    if not target_index.empty:
        # Itera sobre las columnas de la fila de actualización, excluyendo las especificadas
        for col_name, value_to_update in row_update.drop(columns_to_exclude_from_update, errors='ignore').items():
            # Solo actualiza si el valor de origen no es NaN y la columna existe en el DataFrame final
            if pd.notna(value_to_update) and col_name in df_updated_final.columns:
                df_updated_final.loc[target_index, col_name] = value_to_update

print("\nDataFrame final después de la integración de datos (primeras 5 filas):")
display(df_updated_final.head())
print(f"Número total de filas en el DataFrame final: {len(df_updated_final)}")

# Asigna el DataFrame procesado final a df_normalized_global para que esté disponible en celdas futuras
df_normalized_global = df_updated_final.copy()

# Opcional: Guardar el resultado final a un archivo CSV local
output_filename_final = 'Registros_Actualizados_Integrados.csv'
df_normalized_global.to_csv(output_filename_final, index=False)
print(f"\nEl archivo '{output_filename_final}' con los registros integrados ha sido creado localmente.")

Contenido del Google Sheet de Actualizaciones (Sheet A):

,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,autor_congreso_111,...,coau_institucion_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,numero_copia_952_t.1,numero_copia_952_t.2,952_a,952_b
0,18551,NaN,NaN,NaN,NaN,NaN,324.640985/BEE/2018,NaN,Perú. Registro Nacional de Identificación y Es...,NaN,...,NaN,BKS,NaN,324.640985/BEE/2018,NaN,NaN,Ej. 2,NaN,ONPE,ONPE
1,14495,NaN,NaN,NaN,NaN,NaN,REF/352.02585/A81/2000,NaN,Asociación Civil Transparencia (Lima),NaN,...,NaN,BKS,NaN,REF/352.02585/A81/2000,NaN,NaN,NaN,NaN,ONPE,ONPE
2,14496,NaN,NaN,2015-13710,NaN,NaN,364.152/I59/2011-2014,NaN,Instituto Nacional de Estadística e Informátic...,NaN,...,NaN,BKS,NaN,364.152/I59/2011-2014,NaN,NaN,NaN,NaN,ONPE,ONPE
3,15732,NaN,NaN,2015-12936,NaN,NaN,330.985/I59/2011-2014,NaN,Instituto Nacional de Estadística e Informátic...,NaN,...,NaN,BKS,NaN,330.985/I59/2011-2014,NaN,NaN,NaN,NaN,ONPE,ONPE
4,16066,NaN,NaN,NaN,NaN,NaN,324.97293/J89/2012,NaN,República Dominicana. Junta Central Electoral,NaN,...,NaN,BKS,NaN,324.97293/J89/2012,NaN,NaN,NaN,NaN,ONPE,ONPE

DataFrame filtrado basado en 11 biblionumbers únicos de la hoja de actualizaciones:

,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,autor_congreso_111,...,coautor_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,952_a,952_b,numero_copia_952_t.1,numero_copia_952_t.2
843,14022,994513054-4,NaN,NaN,NaN,spa,VIII.3/DOM/2008-5,NaN,Junta Central Electoral,NaN,...,NaN,BKS,BKS,IX.2/001/t.2,00435-001-CAMP007BKS,NaN,ONPE,<NA>,<NA>,<NA>
1877,14495,9968-907-02-2,NaN,NaN,NaN,spa,VIII.3/CR/2002-6,NaN,Tribunal Supremo de Elecciones,NaN,...,NaN,BKS,BKS,VIII.3/CR/2002-7,00908-001-CÓMP005BKS,NaN,ONPE,<NA>,<NA>,<NA>
1878,14496,9968-907-17-0,NaN,NaN,NaN,spa,VIII.3/CR/2002-7,NaN,Tribunal Supremo de Elecciones,NaN,...,NaN,BKS,BKS,L/007/TRI,00909-001-CÓMP005BKS,NaN,ONPE,<NA>,<NA>,<NA>
4265,15732,NaN,NaN,NaN,NaN,spa,NaN,NaN,National Democratic Institute,NaN,...,NaN,BKS,BKS,NaN,02145-001-GUIACHABKS,NaN,ONPE,<NA>,<NA>,<NA>
4266,15732,NaN,NaN,NaN,NaN,spa,NaN,NaN,National Democratic Institute,NaN,...,NaN,BKS,BKS,NaN,02145-002-GUIACHABKS,Ej.2,ONPE,<NA>,<NA>,<NA>

Número de filas después del filtro: 16

Todos los biblionumbers de la hoja de actualizaciones están presentes en el documento global.

Ningún biblionumber tiene más de 3 ejemplares.

DataFrame procesado con ejemplares colapsados y columnas 'Ej.' actualizadas (primeras 5 filas):

,biblionumber_999_c,numero_copia_952_t,numero_copia_952_t.1,numero_copia_952_t.2
0,14022,<NA>,<NA>,<NA>
1,14495,<NA>,<NA>,<NA>
2,14496,<NA>,<NA>,<NA>
3,15732,<NA>,Ej. 2,Ej. 3
4,16066,<NA>,<NA>,<NA>

DataFrame final después de la integración de datos (primeras 5 filas):

,biblionumber_999_c,isbn_020,issn_022,dl_024,fuente_catalogacion_040,idioma_catalogacion_041,cd_dewey_082,autor_persona_100,autor_institucion_110,autor_congreso_111,...,coautor_3,koha_tipo_item_942_c,tipo_item_952_y,dewey_952_o,cod_barras_952_p,numero_copia_952_t,952_a,952_b,numero_copia_952_t.1,numero_copia_952_t.2
0,14022,994513054-4,None,2015-17747,None,spa,345.8502523/D61,None,Perú. Defensoría del Pueblo,None,...,None,BKS,BKS,345.8502523/D61,00435-001-CAMP007BKS,<NA>,ONPE,ONPE,<NA>,<NA>
1,14495,9968-907-02-2,None,None,None,spa,REF/352.02585/A81/2000,None,Asociación Civil Transparencia (Lima),None,...,None,BKS,BKS,REF/352.02585/A81/2000,00908-001-CÓMP005BKS,<NA>,ONPE,ONPE,<NA>,<NA>
2,14496,9968-907-17-0,None,2015-13710,None,spa,364.152/I59/2011-2014,None,Instituto Nacional de Estadística e Informátic...,None,...,None,BKS,BKS,364.152/I59/2011-2014,00909-001-CÓMP005BKS,<NA>,ONPE,ONPE,<NA>,<NA>
3,15732,None,None,2015-12936,None,spa,330.985/I59/2011-2014,None,Instituto Nacional de Estadística e Informátic...,None,...,None,BKS,BKS,330.985/I59/2011-2014,02145-001-GUIACHABKS,<NA>,ONPE,ONPE,Ej. 2,Ej. 3
4,16066,None,None,None,None,spa,324.97293/J89/2012,None,República Dominicana. Junta Central Electoral,None,...,None,BKS,BKS,324.97293/J89/2012,02479-001-INVE014BKS,<NA>,ONPE,ONPE,<NA>,<NA>

Número total de filas en el DataFrame final: 11

El archivo 'Registros_Actualizados_Integrados.csv' con los registros integrados ha sido creado localmente.

# **5. Pasando de google sheets a mrc**

In [ ]:
import pandas as pd
from pymarc import Record, Field, MARCWriter, Subfield

df = df_normalized_global # Usamos df_normalized_global, que es el resultado de la integración

output_filename = "koha_Libros_Actualizados_from_GoogleSheet.mrc"
writer = MARCWriter(open(output_filename, "wb"))

for i, row in df.iterrows():
    record = Record()

    # 020 ISBN
    if 'isbn_020' in row and pd.notna(row['isbn_020']):
        record.add_field(
            Field(
                tag='020',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['isbn_020']))]
            )
        )

    # 022 ISSN
    if 'issn_022' in row and pd.notna(row['issn_022']):
        record.add_field(
            Field(
                tag='022',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['issn_022']))]
            )
        )

    # 024 DL
    if 'dl_024' in row and pd.notna(row['dl_024']):
        record.add_field(
            Field(
                tag='024',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['dl_024']))]
            )
        )

    # 040 Fuente de Catalogación
    subfields_040 = []
    if 'fuente_catalogacion_040' in row and pd.notna(row['fuente_catalogacion_040']):
        subfields_040.append(Subfield('c', str(row['fuente_catalogacion_040'])))

    if subfields_040:
        record.add_field(
            Field(
                tag='040',
                indicators=[' ',' '],
                subfields=subfields_040
            )
        )

    # 041 Idioma de Catalogación
    if 'idioma_catalogacion_041' in row and pd.notna(row['idioma_catalogacion_041']):
        record.add_field(
            Field(
                tag='041',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['idioma_catalogacion_041']))]
            )
        )

    # 082 Clasificación Decimal Dewey
    if 'cd_dewey_082' in row and pd.notna(row['cd_dewey_082']):
        record.add_field(
            Field(
                tag='082',
                indicators=['0','0'],
                subfields=[Subfield('a', str(row['cd_dewey_082']))]
            )
        )

    # 100 Autor Personal
    if 'autor_persona_100' in row and pd.notna(row['autor_persona_100']):
        record.add_field(
            Field(
                tag='100',
                indicators=['1',' '],
                subfields=[Subfield('a', str(row['autor_persona_100']))]
            )
        )

    # 110 Autor Institución
    if 'autor_institucion_110' in row and pd.notna(row['autor_institucion_110']):
        record.add_field(
            Field(
                tag='110',
                indicators=['2',' '],
                subfields=[Subfield('a', str(row['autor_institucion_110']))]
            )
        )

    # 111 Autor Congreso
    if 'autor_congreso_111' in row and pd.notna(row['autor_congreso_111']):
        record.add_field(
            Field(
                tag='111',
                indicators=['2',' '],
                subfields=[Subfield('a', str(row['autor_congreso_111']))]
            )
        )

    # 630 Asiento de Materia - Título Uniforme
    if 'materia_titulo_uniforme_630' in row and pd.notna(row['materia_titulo_uniforme_630']):
        record.add_field(
            Field(
                tag='630',
                indicators=['0','0'],
                subfields=[Subfield('a', str(row['materia_titulo_uniforme_630']))]
            )
        )

    # 245 Título
    if 'titulo_245' in row and pd.notna(row['titulo_245']):
        record.add_field(
            Field(
                tag='245',
                indicators=['1','0'],
                subfields=[Subfield('a', str(row['titulo_245']))]
            )
        )

    # 246 Variantes del Título
    if 'varian_del_título_246' in row and pd.notna(row['varian_del_título_246']):
        record.add_field(
            Field(
                tag='246',
                indicators=['3',' '],
                subfields=[Subfield('a', str(row['varian_del_título_246']))]
            )
        )

    # 250 Mención de Edición
    if 'edicion_250' in row and pd.notna(row['edicion_250']):
        record.add_field(
            Field(
                tag='250',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['edicion_250']))]
            )
        )

    # 260 Publicación
    subfields_260 = []
    if 'lugar_publicacion_260' in row and pd.notna(row['lugar_publicacion_260']):
        subfields_260.append(Subfield('a', str(row['lugar_publicacion_260'])))
    if 'editorial_260' in row and pd.notna(row['editorial_260']):
        subfields_260.append(Subfield('b', str(row['editorial_260'])))
    if 'anio_260' in row and pd.notna(row['anio_260']):
        # Corrected: convert directly to string, avoiding int() for potential non-numeric values
        subfields_260.append(Subfield('c', str(row['anio_260'])))

    if subfields_260:
        record.add_field(
            Field(
                tag='260',
                indicators=[' ',' '],
                subfields=subfields_260
            )
        )

    # 300 Descripción Física
    if 'descripcion_fisica_300' in row and pd.notna(row['descripcion_fisica_300']):
        record.add_field(
            Field(
                tag='300',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['descripcion_fisica_300']))]
            )
        )

    # 490 Mención de Serie 1
    subfields_490_1 = []
    if 'serie_1_490' in row and pd.notna(row['serie_1_490']):
        subfields_490_1.append(Subfield('a', str(row['serie_1_490'])))
    if 'serie_1_490_v' in row and pd.notna(row['serie_1_490_v']):
        subfields_490_1.append(Subfield('v', str(row['serie_1_490_v'])))
    if subfields_490_1:
        record.add_field(
            Field(
                tag='490',
                indicators=['1',' '],
                subfields=subfields_490_1
            )
        )

    # 490 Mención de Serie 2
    subfields_490_2 = []
    if 'serie_2_490' in row and pd.notna(row['serie_2_490']):
        subfields_490_2.append(Subfield('a', str(row['serie_2_490'])))
    if 'serie_2_490_v' in row and pd.notna(row['serie_2_490_v']):
        subfields_490_2.append(Subfield('v', str(row['serie_2_490_v'])))
    if subfields_490_2:
        record.add_field(
            Field(
                tag='490',
                indicators=['1',' '],
                subfields=subfields_490_2
            )
        )

    # 500 Nota General
    if 'nota_general_500' in row and pd.notna(row['nota_general_500']):
        record.add_field(
            Field(
                tag='500',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['nota_general_500']))]
            )
        )

    # 505 Formatted Contents Note
    if 'formatted_contents_note_505' in row and pd.notna(row['formatted_contents_note_505']):
        record.add_field(
            Field(
                tag='505',
                indicators=['0',' '],
                subfields=[Subfield('a', str(row['formatted_contents_note_505']))]
            )
        )

    # 520 Resumen
    if 'resumen_520' in row and pd.notna(row['resumen_520']):
        record.add_field(
            Field(
                tag='520',
                indicators=[' ',' '],
                subfields=[Subfield('a', str(row['resumen_520']))]
            )
        )

    # 600 Asiento de Materia - Persona
    for col_suffix in ['1', '2', '3', '4']:
        col_name = f'materia_persona_{col_suffix}_600'
        if col_name in row and pd.notna(row[col_name]):
            record.add_field(
                Field(
                    tag='600',
                    indicators=['1','0'],
                    subfields=[Subfield('a', str(row[col_name]).strip())]
                )
            )

    # 610 Asiento de Materia - Institución
    for col_suffix in ['1', '2', '3', '4']:
        col_name = f'materia_institucion_{col_suffix}_610'
        if col_name in row and pd.notna(row[col_name]):
            record.add_field(
                Field(
                    tag='610',
                    indicators=['2','0'],
                    subfields=[Subfield('a', str(row[col_name]).strip())]
                )
            )

    # 650 Asiento de Materia - Término Temático (Generic)
    for col_suffix in ['1', '2', '3', '4']:
        col_name = f'materia_{col_suffix}'
        if col_name in row and pd.notna(row[col_name]):
            record.add_field(
                Field(
                    tag='650',
                    indicators=[' ','0'],
                    subfields=[Subfield('a', str(row[col_name]).strip())]
                )
            )

    # 651 Asiento de Materia - Término Geográfico
    for col_suffix in ['1', '2']:
        col_name = f'materia_geogra_{col_suffix}'
        if col_name in row and pd.notna(row[col_name]):
            record.add_field(
                Field(
                    tag='651',
                    indicators=[' ','0'],
                    subfields=[Subfield('a', str(row[col_name]).strip())]
                )
            )

    # 655 Término de Indización - Género/Forma
    if 'materia_forma_655' in row and pd.notna(row['materia_forma_655']):
        record.add_field(
            Field(
                tag='655',
                indicators=[' ','7'],
                subfields=[Subfield('a', str(row['materia_forma_655'])), Subfield('2', 'lcgft')]
            )
        )

    # 700 Asiento Secundario - Nombre Personal (coautor_1, coautor_2, coautor_3)
    if 'coautor_1' in row and pd.notna(row['coautor_1']):
        record.add_field(
            Field(
                tag='700',
                indicators=['1',' '],
                subfields=[Subfield('a', str(row['coautor_1'])), Subfield('e', 'coautor')]
            )
        )
    if 'coautor_2' in row and pd.notna(row['coautor_2']):
        record.add_field(
            Field(
                tag='700',
                indicators=['1',' '],
                subfields=[Subfield('a', str(row['coautor_2'])), Subfield('e', 'coautor')]
            )
        )
    if 'coautor_3' in row and pd.notna(row['coautor_3']):
        record.add_field(
            Field(
                tag='700',
                indicators=['1', ' '],
                subfields=[Subfield('a', str(row['coautor_3'])), Subfield('e', 'coautor')]
            )
        )

    # 710 Asiento Secundario - Nombre Corporativo (coau_institución_1, etc.)
    for col_suffix in ['1', '2', '3']:
        col_name = f'coau_institución_{col_suffix}'
        if col_name in row and pd.notna(row[col_name]):
            record.add_field(
                Field(
                    tag='710',
                    indicators=['2',' '],
                    subfields=[Subfield('a', str(row[col_name]).strip()), Subfield('e', 'coautor')]
                )
            )

    # 942 Koha Item Type
    if 'koha_tipo_item_942_c' in row and pd.notna(row['koha_tipo_item_942_c']):
        record.add_field(
            Field(
                tag='942',
                indicators=[' ',' '],
                subfields=[Subfield('c', str(row['koha_tipo_item_942_c']))]
            )
        )

    # 952 Ítems (Múltiples para ejemplares)
    # Capturar subcampos comunes para todos los 952
    common_subfields_for_952 = []
    if 'tipo_item_952_y' in row and pd.notna(row['tipo_item_952_y']):
        common_subfields_for_952.append(Subfield('y', str(row['tipo_item_952_y'])))
    if 'dewey_952_o' in row and pd.notna(row['dewey_952_o']):
        common_subfields_for_952.append(Subfield('o', str(row['dewey_952_o'])))
    if 'cod_barras_952_p' in row and pd.notna(row['cod_barras_952_p']):
        # Ensure cod_barras is an integer if present, otherwise append as string
        try:
            common_subfields_for_952.append(Subfield('p', str(int(row['cod_barras_952_p']))))
        except ValueError:
            common_subfields_for_952.append(Subfield('p', str(row['cod_barras_952_p'])))
    if '952_a' in row and pd.notna(row['952_a']):
        common_subfields_for_952.append(Subfield('a', str(row['952_a'])))
    if '952_b' in row and pd.notna(row['952_b']):
        common_subfields_for_952.append(Subfield('b', str(row['952_b'])))

    # Columnas para los números de copia. No se define default_t_value aquí,
    # el comportamiento de 't' vacío se gestiona a continuación.
    copy_columns_to_process = ['numero_copia_952_t', 'numero_copia_952_t.1', 'numero_copia_952_t.2']

    at_least_one_952_generated = False

    for idx, col_name in enumerate(copy_columns_to_process):
        t_subfield_value = None

        if col_name in row and pd.notna(row[col_name]):
            t_subfield_value = str(row[col_name])

        if t_subfield_value is not None:
            # Si hay un valor explícito para 't', se añade un 952 con los subcampos comunes y el 't'
            current_copy_subfields_952 = list(common_subfields_for_952)
            current_copy_subfields_952.append(Subfield('t', t_subfield_value))
            record.add_field(
                Field(
                    tag='952',
                    indicators=[' ',' '],
                    subfields=current_copy_subfields_952
                )
            )
            at_least_one_952_generated = True
        elif idx == 0 and not at_least_one_952_generated and common_subfields_for_952:
            # Este es el caso del primer ejemplar (col_name 'numero_copia_952_t') cuando está vacío,
            # pero existen otros subcampos comunes (y, o, p). Se añade un 952 sin $t.
            record.add_field(
                Field(
                    tag='952',
                    indicators=[' ',' '],
                    subfields=list(common_subfields_for_952)
                )
            )
            at_least_one_952_generated = True

    # Si no se generó ningún 952 y no hay ningún subcampo común, entonces no se añade nada.
    # Si se generó al menos uno, o si el idx==0 y hay common_subfields_for_952, ya está cubierto.

    # 999 Biblionumber (Koha specific)
    if 'biblionumber_999_c' in row and pd.notna(row['biblionumber_999_c']):
        # Corrected: convert directly to string, avoiding int() for potential non-numeric values
        record.add_field(
            Field(
                tag='999',
                indicators=[' ',' '],
                subfields=[Subfield('c', str(row['biblionumber_999_c']))]
            )
        )

    writer.write(record)

writer.close()

print(f"Archivo MARC '{output_filename}' generado correctamente desde Google Sheet.")

Archivo MARC 'koha_Libros_Actualizados_from_GoogleSheet.mrc' generado correctamente desde Google Sheet.

# **5.1. Vista previa del archivo MARC**

In [ ]:
from pymarc import MARCReader

marc_file = 'koha_Libros_Actualizados_from_GoogleSheet.mrc'

print(f"Previsualizando los primeros 5 registros de '{marc_file}':\n")

with open(marc_file, 'rb') as fh:
    reader = MARCReader(fh)
    for i, record in enumerate(reader):
        if i >= 5:
            break
        print(f"--- Registro {i+1} ---")
        print(record)
        print("\n")

Previsualizando los primeros 5 registros de 'koha_Libros_Actualizados_from_GoogleSheet.mrc':

--- Registro 1 ---
=LDR  01134    a2200253   4500
=020  \\$a994513054-4
=024  \\$a2015-17747
=041  \\$aspa
=082  00$a345.8502523/D61
=110  2\$aPerú. Defensoría del Pueblo
=245  10$aFeminicidio íntimo en el Perú : análisis de expedientes judiciales (2012-2015). Octavo Reporte de la Defensoría del Pueblo sobre el cumplimiento de la Ley de Igualdad de Oportunidades entre Mujeres y Hombres (2015)
=250  \\$a1a edición
=260  \\$aLima$bDefensoría del Pueblo$c2015.0
=300  \\$a224 páginas; 24 centímetros
=490  1\$aInformes Defensoriales Infor
=490  1\$a173.0
=505  0\$aContenido: Marco jurídico internacional frente a la violencia contra las mujeres. La política criminal peruana frente al feminicidio íntimo. Actuación del sistema de administración de justicia en los casos de feminicidio íntimo. Hallazgos de la supervisión defensorial.
=650  \0$aViolencia familiar
=650  \0$aMujeres Maltratadas
=650  \0$aHomicidios
=651  \0$aPerú
=942  \\$cBKS
=952  \\$yBKS$o345.8502523/D61$p00435-001-CAMP007BKS$aONPE$bONPE
=999  \\$c14022



--- Registro 2 ---
=LDR  00716    a2200229   4500
=020  \\$a9968-907-02-2
=041  \\$aspa
=082  00$aREF/352.02585/A81/2000
=110  2\$aAsociación Civil Transparencia (Lima)
=245  10$aDirectorio de Alcaldes y municipalidades de Perú 1999-2002
=250  \\$a2a edición
=260  \\$aLima$bAsociación Civil Transparencia$c2000.0
=300  \\$a327 páginas: mapas; 21 centímetros
=650  \0$aAlcaldes
=650  \0$aDirectorios
=650  \0$aGobierno local
=651  \0$aPerú
=700  1\$aCáceres Mauricci, Ronny$ecoautor
=700  1\$aVega Carreazo, Rudecindo$ecoautor
=942  \\$cBKS
=952  \\$yBKS$oREF/352.02585/A81/2000$p00908-001-CÓMP005BKS$aONPE$bONPE
=999  \\$c14495



--- Registro 3 ---
=LDR  01178    a2200229   4500
=020  \\$a9968-907-17-0
=024  \\$a2015-13710
=041  \\$aspa
=082  00$a364.152/I59/2011-2014
=110  2\$aInstituto Nacional de Estadística e Informática (Perú)
=245  10$aHomicidios en el Perú, contándolos uno a uno, 2011-2016 : informe estadístico Nº 3
=260  \\$aLima$bINEI$c2015.0
=300  \\$a148 páginas: ilustraciones; 30 centímetros + 1 mini CD-ROM
=505  0\$aContenido: Muertes violentadas asociadas a hechos delictivos dolosos 2011-2014. Denuncias de homicidios dolosos y culposos - Policía Nacional del Perú 2005-2014. Feminicidio - ministerio Público, 2011-2014. Población con sentencia condantoria por delito de homicidio doloso - Poder Judicial, 2011-2014. Población penal por delito de homicidio doloso y culposo - Instituto Nacional Penitenciario, 2012-2014. Homicidios en el Perú y América, 2012-2013. Aspectos metodológicos.
=650  \0$aHomicidios
=650  \0$aDelitos
=650  \0$aViolencia
=650  \0$aEstadísticas
=651  \0$aPerú
=942  \\$cBKS
=952  \\$yBKS$o364.152/I59/2011-2014$p00909-001-CÓMP005BKS$aONPE$bONPE
=999  \\$c14496



--- Registro 4 ---
=LDR  01199    a2200241   4500
=024  \\$a2015-12936
=041  \\$aspa
=082  00$a330.985/I59/2011-2014
=110  2\$aInstituto Nacional de Estadística e Informática (Perú)
=245  10$aEncuesta nacional de Programas estratégicos 2011-2014
=260  \\$aLima$bINEI$c2015.0
=300  \\$a162 páginas: ilustraciones; 30 centímetros + 1 mini CD-ROM
=505  0\$aContenido: Servicios. Telecomunicación. Infraestructura urbana y acceso a servicios sociales básicos en comunidades rurales. Salud. Tenencia y formalización de la vivienda. Seguridad ciudadana. Acceso a la identidad. Calidad del aire. Atención de incendios, emergencias médicas y exposición a desastres. Discapacidad, programas sociales y autoidentificación étnica.
=650  \0$aIndicadores Sociales
=650  \0$aProgramas Sociales
=650  \0$aDerecho a la Salud
=650  \0$aVivienda
=651  \0$aPerú
=942  \\$cBKS
=952  \\$yBKS$o330.985/I59/2011-2014$p02145-001-GUIACHABKS$aONPE$bONPE
=952  \\$yBKS$o330.985/I59/2011-2014$p02145-001-GUIACHABKS$aONPE$bONPE$tEj. 2
=952  \\$yBKS$o330.985/I59/2011-2014$p02145-001-GUIACHABKS$aONPE$bONPE$tEj. 3
=999  \\$c15732



--- Registro 5 ---
=LDR  00726    a2200193   4500
=041  \\$aspa
=082  00$a324.97293/J89/2012
=110  2\$aRepública Dominicana. Junta Central Electoral
=245  10$aResultados electorales 2012. Elecciones Ordinarias Generales Presidenciales y de Diputados y Diputadas en el Exterior del 20 de mayo del año 2012
=260  \\$aSanto Domingo$bJCE$c2013.0
=300  \\$a237 páginas: ilustraciones, mapas, tablas; 30 centímetros
=650  \0$aResultados electorales
=650  \0$aVoto en el extranjero
=650  \0$aEstadísticas electorales
=650  \0$aElecciones
=651  \0$aRepública Dominicana
=942  \\$cBKS
=952  \\$yBKS$o324.97293/J89/2012$p02479-001-INVE014BKS$aONPE$bONPE
=999  \\$c16066

# **6. Descarga del archivo MARC**

In [ ]:
from google.colab import files

# Nombre del archivo MARC a descargar
output_filename = 'koha_Libros_Actualizados_from_GoogleSheet.mrc'

try:
    files.download(output_filename)
    print(f"El archivo '{output_filename}' se ha descargado exitosamente.")
except Exception as e:
    print(f"Error al intentar descargar el archivo '{output_filename}': {e}")

El archivo 'koha_Libros_Actualizados_from_GoogleSheet.mrc' se ha descargado exitosamente.